name: unit-tests

on:
  push:
    paths:
      - "**.py"
      - "tests/unit/**"
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements-test.txt

      - name: Run UNIT tests
        run: |
          pytest tests/unit -q -m "unit"